# Generated by Django 3.1 on 2021-12-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211128_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='kategorie', max_length=200)),
                ('description', models.CharField(default='bez popisu', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(default='Others', related_name='products', to='store.Category'),
        ),
    ]
